//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebComputer.Admin {
    
    public partial class ActionLog_Delete {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected Microsoft.Web.UI.ScriptManager ScriptManager;
        protected System.Web.UI.WebControls.Panel pnPanelInPut;
        protected Microsoft.Web.UI.UpdatePanel UpdatePanel1;
        protected System.Web.UI.WebControls.DropDownList DDL_ActionDelete;
        protected System.Web.UI.WebControls.RequiredFieldValidator RFV_DDL_ActionDelete;
        protected System.Web.UI.HtmlControls.HtmlTableRow idFromDate;
        protected System.Web.UI.HtmlControls.HtmlTableRow idToDate;
        protected System.Web.UI.WebControls.Button Delete_ActionLog;
    }
}
