//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebComputer.Admin {
    
    public partial class ActionLog_Login {
        protected System.Web.UI.WebControls.Panel PTitle;
        protected System.Web.UI.HtmlControls.HtmlTable Table1;
        protected System.Web.UI.WebControls.Image LampnColspan;
        protected System.Web.UI.WebControls.Panel PSearchArea;
        protected System.Web.UI.HtmlControls.HtmlTable Table2;
        protected System.Web.UI.WebControls.TextBox txtUserName;
        protected System.Web.UI.WebControls.TextBox txtIP;
        protected System.Web.UI.WebControls.Button ActionLoginSearch;
        protected Microsoft.Web.UI.UpdatePanel UpdatePN;
        protected System.Web.UI.WebControls.GridView GV_ActionLogin;
        protected AtlasControlToolkit.CollapsiblePanelExtender CollSpan;
    }
}
