//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebComputer.Admin {
    
    public partial class BannerCat_Edit {
        protected System.Web.UI.WebControls.DropDownList DDL_Language;
        protected System.Web.UI.WebControls.RequiredFieldValidator RFV_Lang;
        protected System.Web.UI.WebControls.TextBox tbCatName;
        protected System.Web.UI.WebControls.RequiredFieldValidator RFV_CatName;
        protected System.Web.UI.WebControls.TextBox tbPagePath;
        protected System.Web.UI.WebControls.CheckBox cbActive;
        protected System.Web.UI.WebControls.Button Edit_BannerCat;
        protected System.Web.UI.HtmlControls.HtmlInputReset ResetForm;
        protected System.Web.UI.HtmlControls.HtmlInputButton Back_AddNew;
    }
}
