//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebComputer.Admin {
    
    public partial class Banner_AddNew {
        protected Microsoft.Web.UI.UpdatePanel UpdatePanel2;
        protected System.Web.UI.WebControls.DropDownList DDL_Language;
        protected System.Web.UI.WebControls.RequiredFieldValidator RFV_Lang;
        protected Microsoft.Web.UI.UpdatePanel UpdatePanel1;
        protected System.Web.UI.WebControls.ListBox LB_CatBanner;
        protected System.Web.UI.WebControls.RequiredFieldValidator RFV_LB_CatBanner;
        protected System.Web.UI.WebControls.DropDownList DDL_TypeLink;
        protected System.Web.UI.WebControls.RequiredFieldValidator RFV_DDL_TypeLink;
        protected System.Web.UI.WebControls.TextBox tbBannerName;
        protected System.Web.UI.WebControls.TextBox tbBannerURL;
        protected System.Web.UI.WebControls.RequiredFieldValidator RFV_tbBannerURL;
        protected System.Web.UI.WebControls.TextBox tbBannerDesc;
        protected System.Web.UI.WebControls.CheckBox cbExpried;
        protected System.Web.UI.WebControls.FileUpload fuImageName;
        protected System.Web.UI.WebControls.RequiredFieldValidator RFV_fuImageName;
        protected System.Web.UI.WebControls.CheckBox cbActive;
        protected System.Web.UI.WebControls.Button AddNew_Banner;
        protected System.Web.UI.HtmlControls.HtmlInputReset ResetForm;
        protected System.Web.UI.HtmlControls.HtmlInputButton Back_AddNew;
    }
}
