//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebComputer.Admin {
    
    public partial class Cat_Pro_Group_Edit {
        protected System.Web.UI.WebControls.DropDownList DDL_Language;
        protected System.Web.UI.WebControls.RequiredFieldValidator RFV_Lang;
        protected System.Web.UI.WebControls.DropDownList DDL_CatId;
        protected System.Web.UI.WebControls.RequiredFieldValidator RFV_DDL_CatId;
        protected System.Web.UI.WebControls.TextBox tbCatProGroupTitle;
        protected System.Web.UI.WebControls.RequiredFieldValidator RFV_RecruitmentTitle;
        protected System.Web.UI.WebControls.CheckBox cbActive;
        protected FredCK.FCKeditorV2.FCKeditor Content_CatProGroup;
        protected System.Web.UI.WebControls.Button btn_CatProGroup_Edit;
        protected System.Web.UI.HtmlControls.HtmlInputReset Reset_Form;
        protected System.Web.UI.HtmlControls.HtmlInputButton Back_Edit;
    }
}
