//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebComputer.Admin {
    
    public partial class Cat_Pro_Group_List {
        protected System.Web.UI.WebControls.Label lbl_Erro;
        protected System.Web.UI.WebControls.GridView GV_CatPro;
        protected System.Web.UI.WebControls.Button CatProGroup_AddNew;
        protected System.Web.UI.WebControls.Button ProCatGroup_Delete;
    }
}
