//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebComputer.Admin {
    
    public partial class Customer_Detail {
        protected System.Web.UI.WebControls.TextBox txt_customer;
        protected System.Web.UI.WebControls.TextBox txtusername;
        protected System.Web.UI.WebControls.TextBox txtPasword;
        protected System.Web.UI.WebControls.TextBox txt_Address;
        protected System.Web.UI.WebControls.TextBox txt_Phone;
        protected System.Web.UI.WebControls.TextBox txt_mail;
        protected System.Web.UI.HtmlControls.HtmlInputButton Back_Edit;
    }
}
