//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebComputer.Admin {
    
    public partial class Customer_Report {
        protected System.Web.UI.WebControls.GridView GridView_Customer;
        protected System.Web.UI.WebControls.DropDownList DropDownList_CusReport;
        protected System.Web.UI.WebControls.Button Btn_ReportCus;
        protected System.Web.UI.WebControls.Label Lbl_Messager;
        protected System.Web.UI.WebControls.GridView Dtg_Report_Customer;
    }
}
