//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebComputer.Admin {
    
    public partial class Customer_List {
        protected System.Web.UI.WebControls.GridView GV_Customer_List;
        protected System.Web.UI.WebControls.Button Customer_Start;
        protected System.Web.UI.WebControls.Button Customer_Off;
        protected System.Web.UI.WebControls.Button Customer_Delete;
    }
}
