//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebComputer.Admin
{

    public partial class Editor_Cat_Delete
    {
        protected System.Web.UI.HtmlControls.HtmlForm form1;
    }
}
