//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebComputer.Admin {
    
    public partial class Editor_AddNew {
        protected System.Web.UI.HtmlControls.HtmlTextArea txtSubject;
        protected System.Web.UI.HtmlControls.HtmlTextArea Brief;
        protected System.Web.UI.WebControls.DropDownList DDL_Status;
        protected Microsoft.Web.UI.UpdatePanel UpdatePanel1;
        protected System.Web.UI.WebControls.DropDownList DDL_Language;
        protected Microsoft.Web.UI.UpdatePanel UpdatePanel12;
        protected System.Web.UI.HtmlControls.HtmlTableCell CMSNews_Cat_Root;
        protected System.Web.UI.WebControls.CheckBox cbNewsHot;
        protected Microsoft.Web.UI.UpdatePanel UpdatePanel2;
        protected System.Web.UI.HtmlControls.HtmlTableCell CMSCatRelate;
        protected FredCK.FCKeditorV2.FCKeditor Content;
        protected System.Web.UI.WebControls.Button News_AddNew;
        protected System.Web.UI.HtmlControls.HtmlInputReset Reset_Form;
        protected System.Web.UI.HtmlControls.HtmlInputButton Back_AddNew;
    }
}
