//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebComputer.Admin {
    
    public partial class FAQs_Edit {
        protected System.Web.UI.WebControls.DropDownList DDL_Lang;
        protected System.Web.UI.WebControls.RequiredFieldValidator RFV_DDL_Lang;
        protected System.Web.UI.WebControls.TextBox txtQ_User;
        protected System.Web.UI.WebControls.TextBox txtQ_Email;
        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator3;
        protected System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidator1;
        protected System.Web.UI.WebControls.TextBox txtAuthor;
        protected System.Web.UI.WebControls.CheckBox txtActive;
        protected System.Web.UI.WebControls.TextBox txtQuestion;
        protected System.Web.UI.WebControls.RequiredFieldValidator RFV_txtQuestion;
        protected FredCK.FCKeditorV2.FCKeditor Content;
        protected System.Web.UI.WebControls.Button FAQ_Edit;
        protected System.Web.UI.HtmlControls.HtmlInputReset ResetForm;
        protected System.Web.UI.HtmlControls.HtmlInputButton Back_Edit;
    }
}
