//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebComputer.Admin {
    
    public partial class Gallery_Category_Edit {
        protected Microsoft.Web.UI.UpdatePanel UpdatePanel1;
        protected System.Web.UI.WebControls.DropDownList DDL_Language;
        protected System.Web.UI.WebControls.RequiredFieldValidator RFV_DDL_Language;
        protected Microsoft.Web.UI.UpdatePanel UpdatePanel2;
        protected System.Web.UI.HtmlControls.HtmlTableCell CMSNews_Cat_Root;
        protected System.Web.UI.WebControls.TextBox txtCatName;
        protected System.Web.UI.WebControls.RequiredFieldValidator RFV_CatName;
        protected System.Web.UI.WebControls.CheckBox cbActive;
        protected System.Web.UI.WebControls.Button Library_CatImage_Edit;
        protected System.Web.UI.HtmlControls.HtmlInputReset Reset_Form;
        protected System.Web.UI.HtmlControls.HtmlInputButton Back_CatImage_Edit;
    }
}
