//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebComputer.Admin {
    
    public partial class Gallery_View {
        protected System.Web.UI.HtmlControls.HtmlTableCell CMSLibraryImage_View;
        protected System.Web.UI.WebControls.Button LibraryImage_Edit;
        protected System.Web.UI.HtmlControls.HtmlInputButton Back_View;
    }
}
