//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebComputer.Admin {
    
    public partial class Gallery_Addnew {
        protected System.Web.UI.HtmlControls.HtmlTableCell DDL_CatId;
        protected System.Web.UI.WebControls.TextBox txtDesc;
        protected System.Web.UI.WebControls.FileUpload fuImg;
        protected System.Web.UI.WebControls.RequiredFieldValidator RFV_Img;
        protected System.Web.UI.WebControls.Button LibraryImage_AddNew;
        protected System.Web.UI.HtmlControls.HtmlInputReset Reset_Form;
        protected System.Web.UI.HtmlControls.HtmlInputButton Back_AddNew;
    }
}
