//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebComputer.Admin {
    
    public partial class Gallery_list {
        protected System.Web.UI.WebControls.Panel PTitle;
        protected System.Web.UI.HtmlControls.HtmlTable Table1;
        protected System.Web.UI.WebControls.Image LampnColspan;
        protected System.Web.UI.WebControls.Panel PSearchArea;
        protected System.Web.UI.HtmlControls.HtmlTable Table2;
        protected System.Web.UI.HtmlControls.HtmlTableCell DDL_CatId;
        protected System.Web.UI.WebControls.TextBox txtSearch;
        protected System.Web.UI.WebControls.Button bntSearch;
        protected System.Web.UI.WebControls.DataList DL_Images;
        protected System.Web.UI.WebControls.Button LibraryImage_AddNew;
        protected System.Web.UI.WebControls.Button LibraryImage_Delete;
        protected System.Web.UI.WebControls.Label Label1;
        protected System.Web.UI.WebControls.HyperLink lnkPrev;
        protected System.Web.UI.WebControls.Label ListPage;
        protected System.Web.UI.WebControls.HyperLink lnkNext;
        protected AtlasControlToolkit.CollapsiblePanelExtender LampnCollSpan;
    }
}
