//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebComputer.Admin {
    
    public partial class Logo_Category {
        protected System.Web.UI.WebControls.GridView GV_LogoCategory;
        protected System.Web.UI.WebControls.Button Submit_CatLogo_AddNew;
        protected System.Web.UI.WebControls.Button Submit_CatLogo_Delete;
        protected System.Web.UI.WebControls.Button bntback;
    }
}
