//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebComputer.Admin {
    
    public partial class Logo_list {
        protected System.Web.UI.WebControls.DataList DL_Logo;
        protected System.Web.UI.WebControls.Button btDeleteLogo;
        protected System.Web.UI.WebControls.Button bntback;
        protected System.Web.UI.WebControls.Label Label1;
        protected System.Web.UI.WebControls.HyperLink lnkPrev;
        protected System.Web.UI.WebControls.Label ListPage;
        protected System.Web.UI.WebControls.HyperLink lnkNext;
    }
}
