//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebComputer.Admin {
    
    public partial class Member_YourAccount {
        protected System.Web.UI.WebControls.DropDownList DDL_GroupMember;
        protected System.Web.UI.WebControls.TextBox txtUserName;
        protected System.Web.UI.WebControls.CheckBox chkIsActive;
        protected System.Web.UI.WebControls.TextBox txtFullName;
        protected System.Web.UI.WebControls.TextBox txtAddress;
        protected System.Web.UI.WebControls.DropDownList DDL_Sex;
        protected System.Web.UI.WebControls.TextBox txtCompany;
        protected System.Web.UI.WebControls.TextBox txtPosi;
        protected System.Web.UI.WebControls.TextBox txtEmail;
        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator3;
        protected System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidator1;
        protected System.Web.UI.WebControls.TextBox txtTel;
        protected System.Web.UI.WebControls.TextBox txtMobi;
        protected System.Web.UI.WebControls.TextBox txtFax;
        protected System.Web.UI.WebControls.Button Member_Edit;
        protected System.Web.UI.HtmlControls.HtmlInputButton Back_Edit;
    }
}
