//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebComputer.Admin {
    
    public partial class NewHangSX {
        protected System.Web.UI.WebControls.TextBox txt_ProName;
        protected System.Web.UI.WebControls.TextBox TextBox1;
        protected System.Web.UI.WebControls.Button Hang_Add;
        protected System.Web.UI.WebControls.Button Hang_Delete;
        protected System.Web.UI.WebControls.GridView GV_Prov_List;
    }
}
