//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebComputer.Admin {
    
    public partial class OrderDetails {
        protected System.Web.UI.WebControls.Label Label2;
        protected System.Web.UI.WebControls.Label lblOrderID;
        protected System.Web.UI.WebControls.Label lblOrderDate;
        protected System.Web.UI.WebControls.Label lblFullName;
        protected System.Web.UI.WebControls.Label lblEmail;
        protected System.Web.UI.WebControls.Label lblAddress;
        protected System.Web.UI.WebControls.Label lblPhoneNo;
        protected System.Web.UI.WebControls.Label lblrecFullName;
        protected System.Web.UI.WebControls.Label lblrecAddress;
        protected System.Web.UI.WebControls.GridView grvMain;
        protected System.Web.UI.WebControls.Label lblStatusOrder;
        protected System.Web.UI.WebControls.RadioButton rblStatus;
        protected System.Web.UI.WebControls.Label lblTotal;
        protected System.Web.UI.WebControls.Button btnUpdateStatusOrder;
        protected System.Web.UI.WebControls.Label lblError;
    }
}
