//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebComputer.Admin {
    
    public partial class OrderBillDetails {
        protected System.Web.UI.WebControls.Label lblEmployee;
        protected System.Web.UI.WebControls.Label lblBuyDate;
        protected System.Web.UI.WebControls.Label lblProvName;
        protected System.Web.UI.WebControls.Label lblTotal;
        protected System.Web.UI.WebControls.Label lblToPay;
        protected System.Web.UI.WebControls.Label lblRemain;
        protected System.Web.UI.WebControls.GridView grvMain;
    }
}
