//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebComputer.Admin {
    
    public partial class OrderBill_Add {
        protected System.Web.UI.WebControls.Label lblError;
        protected System.Web.UI.WebControls.TextBox txtEmployee;
        protected System.Web.UI.WebControls.Label lblBuyDate;
        protected System.Web.UI.WebControls.DropDownList ddlProvName;
        protected System.Web.UI.WebControls.HyperLink hplAddProvider;
        protected System.Web.UI.WebControls.Label lblCat;
        protected System.Web.UI.WebControls.DropDownList ddlCategory;
        protected System.Web.UI.WebControls.Label lblProduct;
        protected System.Web.UI.WebControls.DropDownList ddlProduct;
        protected System.Web.UI.WebControls.Label lblSubCat;
        protected System.Web.UI.WebControls.DropDownList ddlSubCategory;
        protected System.Web.UI.WebControls.Label lblQuantity;
        protected System.Web.UI.WebControls.TextBox txtQuantity;
        protected System.Web.UI.WebControls.Label lblPrice;
        protected System.Web.UI.WebControls.TextBox txtPrice;
        protected System.Web.UI.WebControls.Label lblDescription;
        protected System.Web.UI.WebControls.TextBox txtDescription;
        protected System.Web.UI.WebControls.Button btnAddToCard;
        protected System.Web.UI.WebControls.Literal Literal1;
        protected System.Web.UI.WebControls.Repeater Repeater1;
        protected System.Web.UI.WebControls.Label lblTitle;
        protected System.Web.UI.WebControls.Label lblTotal;
        protected System.Web.UI.WebControls.Label lblToPay;
        protected System.Web.UI.WebControls.TextBox txtToPay;
        protected System.Web.UI.WebControls.Label lblMoney;
        protected System.Web.UI.WebControls.Button btnAddToBill;
    }
}
