//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebComputer.Admin {
    
    public partial class PaymentOrder {
        protected System.Web.UI.WebControls.Label lblError;
        protected System.Web.UI.WebControls.GridView grvMain;
        protected System.Web.UI.WebControls.Button btnAddPaymentOrder;
    }
}
