//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebComputer.Admin {
    
    public partial class PaymentOrder_Add {
        protected System.Web.UI.WebControls.Label lblError;
        protected System.Web.UI.WebControls.Label lbl;
        protected System.Web.UI.WebControls.Label lblEmployee;
        protected System.Web.UI.WebControls.DropDownList ddlProvName;
        protected System.Web.UI.WebControls.Label lblTotalArrears;
        protected System.Web.UI.WebControls.Label lblTotal;
        protected System.Web.UI.WebControls.TextBox txtQuantity;
        protected System.Web.UI.WebControls.Label lblCreatedDate;
        protected System.Web.UI.WebControls.TextBox txtReasonPayment;
        protected System.Web.UI.WebControls.Button btnAddPaymentOrder;
        protected System.Web.UI.WebControls.Button btnAddPayment;
    }
}
