//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebComputer.Admin {
    
    public partial class Product_Edit {
        protected System.Web.UI.WebControls.TextBox txtSubject;
        protected System.Web.UI.WebControls.TextBox Brief;
        protected System.Web.UI.WebControls.TextBox Textintro;
        protected System.Web.UI.WebControls.TextBox TextCashby;
        protected System.Web.UI.WebControls.DropDownList DDCashby;
        protected System.Web.UI.WebControls.TextBox Text_Quatity;
        protected System.Web.UI.WebControls.DropDownList DDL_Status;
        protected Microsoft.Web.UI.UpdatePanel UpdatePanel1;
        protected System.Web.UI.WebControls.DropDownList DDL_Language;
        protected Microsoft.Web.UI.UpdatePanel UpdatePanel12;
        protected System.Web.UI.HtmlControls.HtmlTableCell CMSProduct_Cat_Root;
        protected System.Web.UI.WebControls.CheckBox cbProductHot;
        protected System.Web.UI.WebControls.CheckBox cbProductOnHomePage;
        protected System.Web.UI.WebControls.Panel PTitle;
        protected System.Web.UI.HtmlControls.HtmlTable Table1;
        protected System.Web.UI.WebControls.Image LampnColspan;
        protected System.Web.UI.WebControls.Panel PSearchArea;
        protected System.Web.UI.HtmlControls.HtmlTable Table2;
        protected Microsoft.Web.UI.UpdatePanel IDGallery;
        protected System.Web.UI.WebControls.DataList DL_Images;
        protected Microsoft.Web.UI.UpdatePanel PUpload;
        protected System.Web.UI.WebControls.FileUpload fuImg;
        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
        protected System.Web.UI.WebControls.Button LibraryImage_AddNew;
        protected System.Web.UI.WebControls.Button LibraryImage_Delete;
        protected FredCK.FCKeditorV2.FCKeditor Content;
        protected System.Web.UI.WebControls.Button Products_Edit;
        protected System.Web.UI.HtmlControls.HtmlInputReset Reset_Form;
        protected System.Web.UI.HtmlControls.HtmlInputButton Back_Edit;
        protected AtlasControlToolkit.CollapsiblePanelExtender LampnCollSpan;
    }
}
