//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebComputer.Admin {
    
    public partial class Product_List {
        protected System.Web.UI.WebControls.Panel PTitle;
        protected System.Web.UI.HtmlControls.HtmlTable Table1;
        protected System.Web.UI.WebControls.Image LampnColspan;
        protected System.Web.UI.WebControls.Panel PSearchArea;
        protected System.Web.UI.HtmlControls.HtmlTable Table2;
        protected System.Web.UI.HtmlControls.HtmlTableCell CMSProduct_Cat_Root;
        protected System.Web.UI.WebControls.TextBox txtSearch;
        protected System.Web.UI.WebControls.Button bntSearch;
        protected System.Web.UI.WebControls.Label lblErro;
        protected System.Web.UI.WebControls.GridView GV_Product_List;
        protected System.Web.UI.WebControls.Button Product_Delete;
        protected System.Web.UI.WebControls.Button Product_Start;
        protected System.Web.UI.WebControls.Button Product_Off;
        protected System.Web.UI.WebControls.Button Btn_AddNewProduct;
        protected AtlasControlToolkit.CollapsiblePanelExtender LampnCollSpan;
    }
}
