//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebComputer.Admin {
    
    public partial class Report_Other {
        protected System.Web.UI.WebControls.Label Label2;
        protected System.Web.UI.WebControls.DropDownList DropDownList_ReportOther;
        protected System.Web.UI.WebControls.TextBox txt_YearReport;
        protected System.Web.UI.WebControls.Button btn_ThongKeKhac;
        protected System.Web.UI.WebControls.Label lbl_Messager;
        protected System.Web.UI.WebControls.GridView GridView_ReportOther;
    }
}
