//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebComputer.Home {
    
    public partial class Build {
        protected System.Web.UI.WebControls.DropDownList DropDownList1;
        protected System.Web.UI.WebControls.SqlDataSource SqlDataSource1;
        protected System.Web.UI.WebControls.DropDownList DropDownList2;
        protected System.Web.UI.WebControls.SqlDataSource SqlDataSource3;
        protected System.Web.UI.WebControls.DropDownList DropDownList3;
        protected System.Web.UI.WebControls.SqlDataSource SqlDataSource2;
        protected System.Web.UI.WebControls.DropDownList DropDownList4;
        protected System.Web.UI.WebControls.SqlDataSource SqlDataSource4;
        protected System.Web.UI.WebControls.DropDownList DropDownList5;
        protected System.Web.UI.WebControls.SqlDataSource SqlDataSource5;
        protected System.Web.UI.WebControls.DropDownList DropDownList6;
        protected System.Web.UI.WebControls.SqlDataSource SqlDataSource6;
        protected System.Web.UI.WebControls.DropDownList DropDownList7;
        protected System.Web.UI.WebControls.SqlDataSource SqlDataSource7;
        protected System.Web.UI.WebControls.DropDownList DropDownList8;
        protected System.Web.UI.WebControls.SqlDataSource SqlDataSource8;
        protected System.Web.UI.WebControls.DropDownList DropDownList9;
        protected System.Web.UI.WebControls.SqlDataSource SqlDataSource9;
        protected System.Web.UI.WebControls.DropDownList DropDownList10;
        protected System.Web.UI.WebControls.SqlDataSource SqlDataSource10;
        protected System.Web.UI.WebControls.DropDownList DropDownList11;
        protected System.Web.UI.WebControls.SqlDataSource SqlDataSource11;
        protected System.Web.UI.WebControls.DropDownList DropDownList12;
        protected System.Web.UI.WebControls.SqlDataSource SqlDataSource12;
        protected System.Web.UI.WebControls.Label lblTotalPrice;
        protected System.Web.UI.WebControls.Button Button2;
        protected System.Web.UI.WebControls.Button Button1;
    }
}
