//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebComputer.Home {
    
    public partial class Cart {
        protected System.Web.UI.WebControls.Label lblName;
        protected System.Web.UI.WebControls.Label lblCost;
        protected System.Web.UI.WebControls.TextBox txtCount;
        protected System.Web.UI.WebControls.Button btnShow;
        protected System.Web.UI.WebControls.Literal Literal1;
    }
}
