//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebComputer.Home {
    
    public partial class Contact {
        protected System.Web.UI.WebControls.TextBox txtFullName;
        protected System.Web.UI.WebControls.RequiredFieldValidator RFV_FullName;
        protected System.Web.UI.WebControls.TextBox txtAddress;
        protected System.Web.UI.WebControls.TextBox txtPhone;
        protected System.Web.UI.WebControls.TextBox txtEmail;
        protected System.Web.UI.WebControls.RequiredFieldValidator RFV_Email;
        protected System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidator1;
        protected System.Web.UI.HtmlControls.HtmlTextArea txtContent;
        protected System.Web.UI.WebControls.RequiredFieldValidator RFV_Content;
        protected System.Web.UI.WebControls.Button Contact_AddNew;
    }
}
