//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebComputer.Home {
    
    public partial class Login {
        protected System.Web.UI.WebControls.ImageButton btnRegister;
        protected System.Web.UI.WebControls.TextBox txtUser;
        protected System.Web.UI.WebControls.TextBox txtPass;
        protected System.Web.UI.WebControls.ImageButton btnSubmit;
        protected System.Web.UI.WebControls.Literal Literal1;
    }
}
