//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebComputer.Home {
    
    public partial class PreviewOrder {
        protected System.Web.UI.WebControls.TextBox txtName;
        protected System.Web.UI.WebControls.TextBox txtAddress;
        protected System.Web.UI.WebControls.TextBox txtEmail;
        protected System.Web.UI.WebControls.TextBox txtTel;
        protected System.Web.UI.WebControls.Label Label1;
        protected System.Web.UI.WebControls.Label lblName;
        protected System.Web.UI.WebControls.TextBox txtDeliveryName;
        protected System.Web.UI.WebControls.Label lblAddress;
        protected System.Web.UI.WebControls.TextBox txtDeliveryAddress;
        protected System.Web.UI.WebControls.RadioButton rdgiaohangtantay;
        protected System.Web.UI.WebControls.RadioButton rdGiaohangquabuudien;
        protected System.Web.UI.WebControls.RadioButton rdChuyenPhatNhanh;
        protected System.Web.UI.WebControls.RadioButton rdGiaohangcaptop;
        protected System.Web.UI.WebControls.RadioButton rdThanhToanTrucTiep;
        protected System.Web.UI.WebControls.RadioButton rdNhanVienGiaoHangThuTien;
        protected System.Web.UI.WebControls.RadioButton rdChuyenKhoan;
        protected System.Web.UI.WebControls.RadioButton rdGuiQuaBuuDien;
        protected System.Web.UI.WebControls.ImageButton btnPreviewOrder;
    }
}
