//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebComputer.Home {
    
    public partial class ProcessOrder {
        protected System.Web.UI.WebControls.Label lblMessager;
        protected System.Web.UI.WebControls.Label lblCus_name;
        protected System.Web.UI.WebControls.Label lblCus_tel;
        protected System.Web.UI.WebControls.Label lblDeliveryAddress;
        protected System.Web.UI.WebControls.Repeater rptShowCart;
        protected System.Web.UI.WebControls.Label lblTotal;
        protected System.Web.UI.WebControls.Label lblDocso;
        protected System.Web.UI.WebControls.Label lblDelivery;
        protected System.Web.UI.WebControls.Label lblPay;
        protected System.Web.UI.WebControls.ImageButton btnKhangDinh;
        protected System.Web.UI.WebControls.ImageButton btnDelOrder;
        protected System.Web.UI.WebControls.Label Label1;
    }
}
