//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebComputer.Control.Admin {
    
    public partial class Left {
        protected System.Web.UI.HtmlControls.HtmlTableRow GroupList_Id;
        protected System.Web.UI.WebControls.HyperLink HplListMember;
        protected System.Web.UI.HtmlControls.HtmlTableRow GroupAddnew_Id;
        protected System.Web.UI.WebControls.HyperLink HyperLink1;
        protected System.Web.UI.HtmlControls.HtmlTableRow UserAddnew_Id;
        protected System.Web.UI.WebControls.HyperLink HyperLink5;
        protected System.Web.UI.HtmlControls.HtmlTableRow MemberList_Id;
        protected System.Web.UI.WebControls.HyperLink HyperLink6;
        protected System.Web.UI.WebControls.HyperLink HyperLink7;
        protected System.Web.UI.HtmlControls.HtmlTableRow ActionLogLogin_Id;
        protected System.Web.UI.WebControls.HyperLink HyperLink9;
        protected System.Web.UI.HtmlControls.HtmlTableRow ActionLogAction_Id;
        protected System.Web.UI.WebControls.HyperLink HyperLink8;
        protected System.Web.UI.HtmlControls.HtmlTableRow SystemManager_ID;
        protected System.Web.UI.HtmlControls.HtmlTableRow ProManager_id;
        protected System.Web.UI.HtmlControls.HtmlTableRow Cat_Pro_List_Id;
        protected System.Web.UI.WebControls.HyperLink HyperLink11;
        protected System.Web.UI.HtmlControls.HtmlTableRow Cat_Pro_Group_List;
        protected System.Web.UI.WebControls.HyperLink HyperLink12;
        protected System.Web.UI.HtmlControls.HtmlTableRow Pro_List;
        protected System.Web.UI.WebControls.HyperLink HyperLink19;
        protected System.Web.UI.HtmlControls.HtmlTableRow ProductManager_ID;
        protected System.Web.UI.HtmlControls.HtmlTableRow Order_Manager_id;
        protected System.Web.UI.HtmlControls.HtmlTableRow Customer_Id;
        protected System.Web.UI.WebControls.HyperLink HyperLink28;
        protected System.Web.UI.HtmlControls.HtmlTableRow Provider_id;
        protected System.Web.UI.WebControls.HyperLink HyperLink29;
        protected System.Web.UI.HtmlControls.HtmlTableRow Provider_Debt;
        protected System.Web.UI.WebControls.HyperLink HyperLink30;
        protected System.Web.UI.HtmlControls.HtmlTableRow Provider_payed;
        protected System.Web.UI.WebControls.HyperLink HyperLink31;
        protected System.Web.UI.HtmlControls.HtmlTableRow Order_List;
        protected System.Web.UI.WebControls.HyperLink HyperLink22;
        protected System.Web.UI.HtmlControls.HtmlTableRow Order_Eidt;
        protected System.Web.UI.WebControls.HyperLink HyperLink23;
        protected System.Web.UI.HtmlControls.HtmlTableRow OrderManager_ID;
        protected System.Web.UI.HtmlControls.HtmlTableRow Report_Manager_id;
        protected System.Web.UI.HtmlControls.HtmlTableRow Report_Product;
        protected System.Web.UI.WebControls.HyperLink HyperLink14;
        protected System.Web.UI.HtmlControls.HtmlTableRow Report_Order;
        protected System.Web.UI.WebControls.HyperLink HyperLink15;
        protected System.Web.UI.HtmlControls.HtmlTableRow Report_ProMax;
        protected System.Web.UI.WebControls.HyperLink HyperLink16;
        protected System.Web.UI.HtmlControls.HtmlTableRow Report_DateTime;
        protected System.Web.UI.WebControls.HyperLink HyperLink18;
        protected System.Web.UI.HtmlControls.HtmlTableRow ManagerReport_ID;
        protected System.Web.UI.HtmlControls.HtmlTableRow NewsManager_Id;
        protected System.Web.UI.HtmlControls.HtmlTableRow NewsCatManager_Id;
        protected System.Web.UI.WebControls.HyperLink HyperLink2;
        protected System.Web.UI.HtmlControls.HtmlTableRow NewsAddnew_Id;
        protected System.Web.UI.WebControls.HyperLink HyperLink3;
        protected System.Web.UI.HtmlControls.HtmlTableRow NewsManager_List_Id;
        protected System.Web.UI.WebControls.HyperLink HyperLink4;
        protected System.Web.UI.HtmlControls.HtmlTableRow NewsManagerSpace_Id;
        protected System.Web.UI.HtmlControls.HtmlTableRow BannerLogoManager_Id;
        protected System.Web.UI.HtmlControls.HtmlTableRow LogoCat_Id;
        protected System.Web.UI.WebControls.HyperLink HyperLink113;
        protected System.Web.UI.HtmlControls.HtmlTableRow LogoAddnew_Id;
        protected System.Web.UI.WebControls.HyperLink HyperLink114;
        protected System.Web.UI.HtmlControls.HtmlTableRow LogoManager_Id;
        protected System.Web.UI.WebControls.HyperLink HyperLink115;
        protected System.Web.UI.HtmlControls.HtmlTableRow BannerCat_Id;
        protected System.Web.UI.WebControls.HyperLink HyperLink116;
        protected System.Web.UI.HtmlControls.HtmlTableRow BannerAddnew_Id;
        protected System.Web.UI.WebControls.HyperLink HyperLink117;
        protected System.Web.UI.HtmlControls.HtmlTableRow BannerManager_Id;
        protected System.Web.UI.WebControls.HyperLink HyperLink118;
        protected System.Web.UI.HtmlControls.HtmlTableRow DocumentManagerSpace_id;
        protected System.Web.UI.HtmlControls.HtmlTableRow Manager_Gallery_id;
        protected System.Web.UI.HtmlControls.HtmlTableRow CatGallery_id;
        protected System.Web.UI.WebControls.HyperLink HyperLink20;
        protected System.Web.UI.HtmlControls.HtmlTableRow AddNewCatGallry_id;
        protected System.Web.UI.WebControls.HyperLink HyperLink25;
        protected System.Web.UI.HtmlControls.HtmlTableRow GalleryList_id;
        protected System.Web.UI.WebControls.HyperLink HyperLink26;
        protected System.Web.UI.HtmlControls.HtmlTableRow GalleryAdd_id;
        protected System.Web.UI.WebControls.HyperLink HyperLink27;
        protected System.Web.UI.HtmlControls.HtmlTableRow Tr2_2;
        protected System.Web.UI.HtmlControls.HtmlTableRow AdminLibraryImagerList_id;
        protected System.Web.UI.HtmlControls.HtmlTableRow CatImageList_id;
        protected System.Web.UI.WebControls.HyperLink HyperLink33;
        protected System.Web.UI.HtmlControls.HtmlTableRow ImageList_id;
        protected System.Web.UI.WebControls.HyperLink HyperLink34;
        protected System.Web.UI.HtmlControls.HtmlTableRow Tr11;
        protected System.Web.UI.HtmlControls.HtmlTableRow DocumentManager;
        protected System.Web.UI.HtmlControls.HtmlTableRow Tr1;
        protected System.Web.UI.WebControls.HyperLink HyperLink13;
        protected System.Web.UI.HtmlControls.HtmlTableRow Tr9;
        protected System.Web.UI.WebControls.HyperLink HyperLink17;
        protected System.Web.UI.HtmlControls.HtmlTableRow BannerLogoManagerSpace_Id;
        protected System.Web.UI.HtmlControls.HtmlTableRow OtherManager_Id;
        protected System.Web.UI.HtmlControls.HtmlTableRow RecruitManager_Id;
        protected System.Web.UI.WebControls.HyperLink HyperLink10;
        protected System.Web.UI.HtmlControls.HtmlTableRow OtherManagerSpace_Id;
        protected System.Web.UI.HtmlControls.HtmlTableRow FAQs_Manager_id;
        protected System.Web.UI.HtmlControls.HtmlTableRow FAQs_Manager_List;
        protected System.Web.UI.WebControls.HyperLink HyperLink21;
        protected System.Web.UI.HtmlControls.HtmlTableRow FAQs_Manager_Edit;
        protected System.Web.UI.WebControls.HyperLink HyperLink24;
        protected System.Web.UI.HtmlControls.HtmlTableRow Faqs_Managers;
    }
}
